language: node_js
node_js:
- '7'
before_script:
- npm install -g tsd
- npm install -g typings
env: PROJ_RELEASE=false
script: 
- cd $TRAVIS_BUILD_DIR/basic-http-client && npm install && npm run zip
- mv $TRAVIS_BUILD_DIR/basic-http-client/wwwroot/dist.zip $TRAVIS_BUILD_DIR/builds/basic-http-client.zip
- cd $TRAVIS_BUILD_DIR/node-http-json && npm install && npm run zip
- mv $TRAVIS_BUILD_DIR/node-http-json/wwwroot/dist.zip $TRAVIS_BUILD_DIR/builds/node-http-json.zip
deploy:
  - provider: releases
    api_key:
      secure: Zjdw0MLe5Zmo4+vGBRvnCemoHkq5oTAD7hWGeujjENcWb5vh0KfBC20YSKHvckA3Vr6/Ecrm/UnMmrqxyQ8U3hOq1USIXXcedwEBhraW1DT+ZTVI8PK4CvKaHzvQnCPTMgBrhuy2JR0PdH5BWQc1SqfCE7+wpNqO9/SLP0/5v+roOaNCMoXvGMoP2d3j5IeTaqv2PZtkJqhiGAUcXbUu4sM9iJi1j7i/BxtZcgZNUHp4I+CQNqh+SwQ1bxuyjZyXfxykt8cJG/UyE9sl75HXUPcdta6479Wy63O5DDM+Zx9XB1bIEsnPG6ouNiqn5hVgMZydynqoGfiVpSR8gsSFTdJS7k5O3IQLRh5ouLwtTwE41ECUWVUNizak9EL84RBLwqewA3qxcc0jwgH2jbhh17h8rwTDOzivrifxZLnkCpRm9i5bX2r+7FYK0p/C9dS2E0/a2fY+iDYOB2xIO7WJBVNyjf2MZ1L1uIw1qul/NZLNjiRxGi7tmIbQ2sW/+wGfxHEdhsgDuXIx9Yggq+cSMHj+pqGwJj9e6ie2KT6uxNp1htiSkO/XjlXAV7hgo+SbcbZdvXFlblGwfGIQ1/0NW8aI367wsTJ8YoAKUbTArgB2O8hBKLi29dyrhfaOckkLs9EYVRoXUp2nA9PeISLhBeEdXnn2x83J8zJSdhQm4zU=
    local_dir: $TRAVIS_BUILD_DIR/builds
    skip_cleanup: true
    on:
      tags: true
  - provider: s3
    access_key_id: AKIAJLUNOIPXKJRAX3OA
    secret_access_key: 
      secure: JdQZFXz8vQitaoufbwR5e2sITYlThcfbNXf3zhNTETaBEWt52qt8kc3cPhbr6uGkJn3jKuDpSxIQEKGD0HlxtHzGO2t2LP0t7eexkbP/aJuBBBHgrevKTZsefr0BdeJ1LcLEWq6sLeVMlX0Vwou9seCfLDjbY5NNhv+yj1oYo9ekUfU5z1vcOQu5yDaA9+3GA1FzEZeTDWUQOUcZV47w2w/5YXgDaWKXBcL5AN4HNukJCnBV+MBGIp81Gy/e91okswjZ/m8ei3RkGc6+B7VI0pNumWZw/khvZAElJM2TegW6fIF/AnuuKFDGhj5xmCitK4CNqww+DfFPfyvzE3thfmOLYV4OUOgRcGS4hHcB8DKfSvR7acJoTZyP2wtstPihlNQsAvZ0z9kjEhxhLF0oKpS3sY3GyLwp7GkH+Tuq4xzQfwIqoA+JIXth96bF648M02NNyy3ed58nriIEm081pSrUW+u9r1V6iuDWxAJxTT2/245S6LfDXZuci5El9qn7sM3/BjKQzX6BcnsAutO2jCckYYNwhE+eDHdWTV/gSYNlbosHgeG2tD92CMEKtqNi2qbLyOtr+8dYDSjGlAehFz/KPjdyAdA9KnzANXtcQtHgXtzP98LM7JldG/fIWlUGi/sqCnV5pblRDihsi4S+ZWJ2/GeyCVGdv1zWWNzSVsI=
    bucket: mmm.aws.deloys
    region: us-east-1
    acl: public_read
    detect_encoding: true
    default_text_charset: 'utf-8'
    local_dir: $TRAVIS_BUILD_DIR/builds
    skip_cleanup: true
    on:
      tags: true